### ISSUE TITLE
Plugin don't starts automatically

### ISSUE THREAD

**Issue by sergiopvilar** [iamstarkov/STsync#2]
Hello!

I'm using Ubuntu 12.10, I have Package Controll and node.js installed but the plugin don't starts automatically.

I really appreciate this plugin.
Anyone can help? Thanks!

**Comment by iamstarkov** [comment]
I’m happy to read your comments.
I will answer you in two days, ’cause now I have some troubles

**Comment by iamstarkov** [comment]
sorry to say, but please use other sync tool
